### ISSUE TITLE
Getting nsight compute to work with amrvac

### ISSUE THREAD

**Issue by oporth** [amrvac/AGILE-experimental#16]
currently I cannot use Nsight compute with amrvac (ncu or ncu-ui).  It works fine the the toycode though.  
The issue is that amrvac needs to be run with mpirun and Nsight compute needs to attach to the amrvac process that is launched from mpi. 

How do we use Nsight compute with amrvac???

**Comment by loostrum** [comment]
I only know of a single-node solution, which is to run `ncu <options> mpirun amrvac`. I'm not 100% sure this works with Nsight Compute though, it does work with Nsight Systems (which is MPI-aware).

**Comment by oporth** [comment]
I think I figured it out, just launching ncu-ui with mpi, e.g.
mpirun -np 1 ncu-ui

**Comment by oporth** [comment]
Hi Leon, thanks I'll try that out as well. I still had issues getting a usable trace analysis out of it (its not showing me the functions in the amrvac process).  So if someone has a good workflow for profiling, we should share that!
