### ISSUE TITLE
manage to compile with nvhpc

### ISSUE THREAD

**Issue by oporth** [amrvac/AGILE-experimental#2]
There will be issues with mod-random and multigrid. We don't really need mod-random and I have a fix for multigrid which someone (Jannis?) should review though. Let me know if I should share that!

**Comment by jannisteunissen** [comment]
I did update the octree-mg library a while ago for compatibility with the nvidia compiler, and just now also the 'single module' files that are used inside MPI-AMRVAC: https://github.com/jannisteunissen/octree-mg/tree/master/single_module

**Comment by oporth** [comment]
Hi Jannis, should we then include those updated 'single module' files here?  Could you push them also to AGILE-experimental in that case?  

Compilation of our test case with NVHPC seems to work fine.  Thanks @beevageeva .

**Comment by jannisteunissen** [comment]
@oporth I have now pushed a new version that includes a fix similar to the one you did (and I also backported some changes from MPI-AMRVAC to the octree-mg repository)

**Comment by oporth** [comment]
Hi, ok great, thanks!  
I believe @beevageeva is still investigating some weird issues with the auto-tests and a failing 1D compilation.

**Comment by oporth** [comment]
As discussed in monthly call 4th June, issue should be closed as it does not affect the test case of interest.
